### ISSUE TITLE
Auth Token

### ISSUE THREAD

**Issue by daveKoala** [thmsgbrt/nodejs-typescript-express-apollo-graphql-starter#1]
In your excellent example how would you use an Authorization token and have available in resolvers? For example in postman?

```
headers: {
"Authorization":"1234.12345678.1234",
]
```
Any hints?

**Comment by thmsgbrt** [comment]
Hi @daveKoala, 
Sorry for the delay, I didn't see you opened an issue. I hope you found a solution since then :).

If you provide an Authorization Header, you can retrieve it by setting the context property when you create the ApolloServer instance.

```
const server = new ApolloServer({
  // ...
  context: async ({ req }) => {
    let ctx = {
      authorization: req.headers['Authorization']
    };
    return ctx;
  }
// ...
});
```

Then, in your resolvers, you get the context object inside the 3rd arguments: 
```
  // ..
    me(_: void, args: any, ctx: Context): Promise<Something> {
      console.log('HERE', ctx.authorization);
      // Do some validation...
     },
  // ... 
```
